name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright Browsers
      run: pnpm exec playwright install

    - name: Run Playwright Tests
      run: pnpm test

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: reports/

    - name: Upload Playwright Report to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: reports/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
