name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Enable corepack and setup pnpm
      run: |
        corepack enable
        corepack prepare pnpm@8.6.0 --activate

    - name: Verify pnpm Installation
      run: pnpm --version

    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright Browsers
      run: pnpm exec playwright install

    - name: Run Playwright Tests
      run: pnpm test

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report/

    - name: Upload Playwright Report to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: playwright-report/



